import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {Rooms} from '../server/rooms.mjs';import {makeServer} from '../server/index.mjs';import {chooseAIAction,createVersusRace,resolveAction} from '../public/badzone/engine.js';
const cmd=(revision,kind,extra={})=>({protocol:1,requestId:randomUUID(),revision,kind,...extra});
function grid(){const r=new Rooms(),a=r.create('knife'),b=r.join(a.code,'wagon');r.command(a.code,a.token,cmd(b.revision,'ready'));const s=r.command(a.code,b.token,cmd(2,'ready'));return {r,a,b,s}}
test('two seats authenticate, ready, legal turns, receipts, private state, reconnect',()=>{const {r,a,b,s}=grid();assert.equal(s.phase,'race');assert.equal(s.localId,2);assert.ok(!('rng'in s.state));assert.ok(!('token'in s.players[0]));assert.throws(()=>r.get(a.code,'bad'),/access/);assert.throws(()=>r.join(a.code,'runner'),/full/);const action=chooseAIAction(r.find(a.code).state),body=cmd(s.revision,'action',{action});assert.throws(()=>r.command(a.code,b.token,body),/not your turn/);const moved=r.command(a.code,a.token,body);assert.ok(moved.revision>s.revision);assert.deepEqual(r.command(a.code,a.token,body),moved);assert.deepEqual(r.get(a.code,b.token).state,moved.state);assert.throws(()=>r.command(a.code,a.token,{...body,action:{...action,throttle:99}}),/already used/);assert.throws(()=>r.command(a.code,b.token,cmd(s.revision,'action',{action})),/changed/);});
test('malformed, forged, illegal and incompatible commands cannot mutate state',()=>{const {r,a,s}=grid(),before=structuredClone(r.find(a.code).state);for(const body of [cmd(s.revision,'action',{action:{throttle:99,steer:0,tactic:'drive'}}),{...cmd(s.revision,'ready'),protocol:9},cmd(s.revision,'action',{action:{throttle:0,steer:0,tactic:'drive',rng:1}}),{...cmd(s.revision,'action'),state:before}])assert.throws(()=>r.command(a.code,a.token,body));assert.deepEqual(r.find(a.code).state,before)});
test('complete shared races and mutual rematch produce fresh stock grids',()=>{for(let i=0;i<20;i++){const {r,a,b}=grid();let n=0;while(r.find(a.code).phase==='race'&&n++<300){const x=r.find(a.code);r.command(a.code,x.state.turn===0?a.token:b.token,cmd(x.revision,'action',{action:chooseAIAction(x.state)}));}const x=r.find(a.code);assert.equal(x.phase,'result');assert.ok([0,2,null].includes(x.state.result.winner));r.command(a.code,a.token,cmd(x.revision,'rematch'));assert.equal(x.phase,'result');r.command(a.code,b.token,cmd(x.revision,'rematch'));assert.equal(x.phase,'lobby');assert.equal(x.state,null);assert.ok(x.players.every(p=>!p.ready));}});
test('either human wrecking awards the surviving opponent; simultaneous wreck draws',()=>{for(const id of [0,2]){const s=createVersusRace('SYMMETRY','runner','runner');s.turn=id;s.vehicles[id].hull=1;s.vehicles[id].x=0;s.vehicles[id].facing=-1;const next=resolveAction(s,{throttle:0,steer:0,tactic:'drive'});if(next.vehicles[id].wrecked)assert.equal(next.result.winner,id===0?2:0)}const s=createVersusRace('DRAW','runner','runner');s.vehicles[0].wrecked=true;s.vehicles[2].wrecked=true;s.turn=1;assert.equal(resolveAction(s,{throttle:0,steer:0,tactic:'drive'}).result.winner,null)});
test('presence times out and reconnect restores the same seat and state',()=>{let now=1;const r=new Rooms({now:()=>now}),a=r.create('knife');now+=16000;const b=r.join(a.code,'runner');assert.equal(b.players[0].connected,false);const back=r.get(a.code,a.token);assert.equal(back.localId,0);assert.equal(back.players[0].connected,true)});
test('HTTP API enforces CORS, auth, protocol, JSON, and serves the client',async t=>{const server=makeServer({limit:10000});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const base='http://127.0.0.1:'+server.address().port;assert.equal((await fetch(base+'/')).status,200);assert.equal((await fetch(base+'/api/health',{headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await fetch(base+'/api/rooms',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'})).status,400);const response=await fetch(base+'/api/rooms',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://badzone-run.onrender.com'},body:JSON.stringify({protocol:1,type:'knife'})});assert.equal(response.status,201);assert.equal(response.headers.get('access-control-allow-origin'),'https://badzone-run.onrender.com');const a=await response.json();assert.equal((await fetch(base+'/api/rooms/'+a.code)).status,401);const state=await fetch(base+'/api/rooms/'+a.code,{headers:{Authorization:'Bearer '+a.token}});assert.equal(state.status,200)});
