import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';import {makeServer} from '../server/index.mjs';import {Rooms} from '../server/rooms.mjs';import {createVersusRace,HAZARDS,generateTrack} from '../public/badzone/engine.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.BADZONE_PLAYWRIGHT||'playwright'),rooms=new Rooms(),server=makeServer({rooms,limit:100000});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true});const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const dir='docs/polish-evidence';await mkdir(dir,{recursive:true});const checks=[];
async function capture(name){await page.locator('.bz-polished').waitFor();await page.evaluate(async()=>{await document.fonts.ready;await new Promise(requestAnimationFrame)});if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Overflow '+name);await page.screenshot({path:dir+'/'+name+'.png',fullPage:true})}
try{
 for(const width of [320,390,768,1280]){
  await page.setViewportSize({width,height:width===768?1024:width===1280?720:844});await page.goto(base);await page.evaluate(()=>sessionStorage.clear());await page.reload();await capture('landing-'+width);
  await page.locator('#bz-create').click();await page.locator('#bz-room-code').waitFor();await capture('lobby-'+width);const code=await page.locator('#bz-room-code').inputValue(),room=rooms.find(code);const p2=rooms.join(code,'bruiser');room.players.forEach(p=>p.ready=true);room.state=createVersusRace('FOUNDRY-10','knife','bruiser');room.state.vehicles[0].x=1;room.state.vehicles[0].y=9;room.state.vehicles[0].speed=2;room.state.vehicles[2].x=4;room.state.vehicles[2].y=5;room.state.vehicles[1].x=6;room.state.vehicles[1].y=4;room.state.vehicles[3].x=5;room.state.vehicles[3].y=10;room.phase='race';room.revision++;await page.locator('#bz-confirm').waitFor();await capture('race-'+width);
  await page.locator('#bz-throttle-2').click();await page.locator('#bz-steer-2').click();await page.locator('#bz-tactic-shoot').click();await page.locator('#bz-target').selectOption('2');await page.locator('#bz-confirm').focus();await page.keyboard.press('Enter');await page.locator('#bz-event-card').waitFor();await capture('action-'+width);
  await page.locator('#bz-motion').check();const anim=await page.locator('.vs-move').first().evaluate(e=>getComputedStyle(e).animationName);if(anim!=='none')throw Error('Reduced motion failed');
  // Real server snapshot presented through the production client; result fixture is visual QA only.
  room.state.status='done';room.state.vehicles.forEach(v=>v.exited=true);room.state.result={winner:2,reason:'Final section finish',order:[2,1,0,3]};room.phase='result';room.revision++;await page.locator('#bz-rematch').waitFor();await capture('result-'+width);checks.push({width,landing:true,lobby:true,race:true,action:true,result:true,keyboard:true,reducedMotion:true});
 }
 // All hazard surfaces and all 12 chassis headings rendered by the shared art module.
 await page.goto(base+'/visual-slice.html');await page.evaluate(async()=>{const {raceBoard,vehicleArt}=await import('/badzone/visual/art.js'),{createRace,HAZARDS}=await import('/badzone/engine.js');document.body.innerHTML='<main id="art-grid" style="display:grid;grid-template-columns:repeat(3,1fr);gap:16px;background:#101b18;padding:20px"></main>';const root=document.querySelector('#art-grid');for(const hazard of HAZARDS){const s=createRace('ART');s.track.hazard=hazard;s.track.tiles=s.track.tiles.map(t=>t==='wall'||t==='road'?t:['turrets','gloom'].includes(hazard)?'road':hazard);root.insertAdjacentHTML('beforeend',`<section><h2>${hazard}</h2>${raceBoard(s,null)}</section>`)}root.insertAdjacentHTML('beforeend','<section style="grid-column:1/-1"><h2>12 chassis views / NW · N · NE</h2>'+['runner','knife','bruiser','wagon'].map(type=>[-1,0,1].map(f=>`<svg width="100" height="100" viewBox="-32 -32 64 64"><g transform="rotate(${f*45})">${vehicleArt(type,'#edb75a')}</g></svg>`).join('')).join('')+'</section>')});await page.screenshot({path:dir+'/hazards-and-headings.png',fullPage:true});
 if(errors.length)throw Error(errors.join('\n'));await writeFile(dir+'/results.json',JSON.stringify({browser:browser.version(),checks,errors,note:'Screenshots use controlled server fixtures for art QA. Live multiplayer separately verified.'},null,2));console.log('Polish: all five screens at four widths, keyboard, reduced motion, six hazards, 12 headings passed');
}finally{await browser.close();await new Promise(r=>server.close(r))}
